#!/bin/sh

# Start script to load LDD kernel modules
case "$1" in
  start)
    echo "Loading scull module"
    /usr/bin/scull_load
    /usr/bin/module_load faulty
    /usr/bin/module_load hello
    /usr/bin/aesdchar_load
    echo "load hello module"
    modprobe hello
    echo "load aesdchar module"
    modprobe aesdchar
    ;;
  stop)
    echo "Unloading scull module"
    /usr/bin/scull_unload
    /usr/bin/module_unload faulty
    /usr/bin/aesdchar_unload
    echo "unload hello module"
    rmmod hello
    echo "unload aesdchar module"
    rmmod aesdchar
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
